// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBDQcOyUGN3ZGKzUCbDFzcJKapN2BHjI4',
    appId: '1:20610432792:web:0cb4be1725b2fbbe50a86d',
    messagingSenderId: '20610432792',
    projectId: 'gobbleup-4b0ad',
    authDomain: 'gobbleup-4b0ad.firebaseapp.com',
    storageBucket: 'gobbleup-4b0ad.firebasestorage.app',
    measurementId: 'G-W7PM63N0TD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIH-kN7bOnQErtoj3D2ZKB8DAiusNAaQg',
    appId: '1:20610432792:android:7595ace775089d5350a86d',
    messagingSenderId: '20610432792',
    projectId: 'gobbleup-4b0ad',
    storageBucket: 'gobbleup-4b0ad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSxJ502YbM7MVodUxm8UChAJjvmiS-E_U',
    appId: '1:20610432792:ios:aa142d5f928bb37150a86d',
    messagingSenderId: '20610432792',
    projectId: 'gobbleup-4b0ad',
    storageBucket: 'gobbleup-4b0ad.firebasestorage.app',
    iosBundleId: 'com.example.firstApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSxJ502YbM7MVodUxm8UChAJjvmiS-E_U',
    appId: '1:20610432792:ios:aa142d5f928bb37150a86d',
    messagingSenderId: '20610432792',
    projectId: 'gobbleup-4b0ad',
    storageBucket: 'gobbleup-4b0ad.firebasestorage.app',
    iosBundleId: 'com.example.firstApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBDQcOyUGN3ZGKzUCbDFzcJKapN2BHjI4',
    appId: '1:20610432792:web:dc5b33b45fbc553750a86d',
    messagingSenderId: '20610432792',
    projectId: 'gobbleup-4b0ad',
    authDomain: 'gobbleup-4b0ad.firebaseapp.com',
    storageBucket: 'gobbleup-4b0ad.firebasestorage.app',
    measurementId: 'G-D9PGW6M9H0',
  );
}
