name: GobbleUp
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

#  (localizations not required)
#  flutter_localizations:
#    sdk: flutter

  firebase_core: ^3.13.1
  flutter_gen: ^5.10.0
  firebase_auth: ^5.5.4
  firebase_database: ^11.3.7
  flutter_card_swiper: ^7.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.10.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/gobbleup_logo.png"

flutter:
  uses-material-design: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/